### ISSUE TITLE
Background color according to theme

### ISSUE THREAD

**Issue by luciolcv** [thomasbnt/Night_PiHole#5]
Hi, I suggest to change background color according to theme behavior. Actually background color is white while theme is black. In particular I suggest the following change in AdminLTE.min.css:

.layout-boxed {
 background:**#1D2226**
}

It looks way better and more consistent!

**Comment by thomasbnt** [comment]
It's done ! (https://github.com/thomasbnt/Night_Pihole/commit/2fa7b9f2b1015d3fe640f26b1d02e51e4e806969)

For updating the CSS : 

```bash
cd /var/www/html/admin/style/vendor/Night_Pihole
git pull
sudo ./install.sh
```
