### ISSUE TITLE
uninstall issue

### ISSUE THREAD

**Issue by larie438** [thomasbnt/Night_PiHole#8]
I'm getting this message when trying to uninstall:
HEAD is now at b86e4a3 Merge pull request #1247 from pi-hole/release/v5.0
what do I need to do?
Thanks

**Comment by thomasbnt** [comment]
Hello, be sure you are located to ​`/www/html/admin/` on raspbian. Not in root Pi-hole and check `sudo git reset --hard` 🙌🏼

**Comment by larie438** [comment]
I'm in /www/html/admin/ but i get the same message

<img width="601" alt="Screen Shot 2020-07-08 at 00 28 47" src="https://user-images.githubusercontent.com/65664183/86850781-28d54a80-c0b2-11ea-8fb5-8a3c3a628cb8.png">

**Comment by larie438** [comment]
So I manage to remove it using root and the rm -r command.
I was trying to uninstall because after installing it and rebooting nothing changed in the Pi-hole web interface. After installing it again still nothing, the interface is light. I'm Using Pi-hole V5

**Comment by thomasbnt** [comment]
Reload with CTRL + F5 for clear cache maybe?

**Comment by larie438** [comment]
nope, still light. I tried disabling my browser ad block as well but still nothing

**Comment by thomasbnt** [comment]
> So I manage to remove it using root and the rm -r command.
> I was trying to uninstall because after installing it and rebooting nothing changed in the Pi-hole web interface. After installing it again still nothing, the interface is light. I'm Using Pi-hole V5

Rm -r is not the good choice, and if you reset Pi-hole ? With a backup before of your lists etc ☕
